# Generated by Django 2.2.5 on 2019-09-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("channel", models.TextField()),
                ("country", models.CharField(max_length=3)),
                ("os", models.CharField(max_length=10)),
                ("impressions", models.PositiveIntegerField()),
                ("clicks", models.PositiveIntegerField()),
                ("installs", models.PositiveIntegerField()),
                ("spend", models.FloatField()),
                ("revenue", models.FloatField()),
            ],
        ),
    ]
