# Generated by Django 2.2.3 on 2019-07-23 20:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "item_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.TextField(default="")),
                ("price", models.FloatField(default=0)),
                ("market", models.TextField(default="")),
                ("src", models.URLField(default="")),
                ("link", models.URLField(default="")),
                ("out_of_stock", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("product_name", models.TextField(default="")),
                ("brand", models.TextField(default="")),
                ("category", models.TextField(default="")),
                ("src", models.URLField(default="")),
                (
                    "sku_ids",
                    django.contrib.postgres.fields.jsonb.JSONField(default=list),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                ("list_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.PositiveIntegerField()),
                (
                    "sku_ids",
                    django.contrib.postgres.fields.jsonb.JSONField(default=list),
                ),
                ("title", models.CharField(default="", max_length=50)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "sku_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "item_ids",
                    django.contrib.postgres.fields.jsonb.JSONField(default=list),
                ),
                ("digits", models.FloatField(default=0)),
                ("unit", models.CharField(default="", max_length=50)),
                ("size", models.TextField(default="")),
            ],
        ),
    ]
