BOT_NAME = "boat"

SPIDER_MODULES = ["src.spiders"]
NEWSPIDER_MODULE = "src.spiders"

ROBOTSTXT_OBEY = False

FEED_EXPORT_ENCODING = "utf-8"
COOKIES_ENABLED = False

DOWNLOADER_MIDDLEWARES = {"scrapy_crawlera.CrawleraMiddleware": 300}
CRAWLERA_ENABLED = True
CRAWLERA_APIKEY = ""

RETRY_ENABLED = True

AUTOTHROTTLE_ENABLED = True
CRAWLERA_PRESERVE_DELAY = True
