# Generated by Django 2.2.3 on 2019-07-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
